---
namespace: "sceptyre"
name: "ansible_crestron"
description: ""

version: "0.0.2"
readme: "README.md"
authors:
    - "Abdellah Fytahi"
license:
    - "MIT"
repository: "https://www.github.com/Sceptyre/ansible-crestron"
